---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    install_recommends: false
  tags: [ufw]

- name: Add UFW allow rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_allow_ports }}"
  tags: [ufw]

- name: Set UFW default policies
  community.general.ufw:
    policy: "{{ ufw_default_incoming }}"
    direction: incoming
  tags: [ufw]

- name: Set UFW default outgoing policy
  community.general.ufw:
    policy: "{{ ufw_default_outgoing }}"
    direction: outgoing
  tags: [ufw]

- name: Enable UFW
  community.general.ufw:
    state: enabled
  tags: [ufw]

- name: Verify UFW status
  ansible.builtin.command: ufw status verbose
  register: ufw_status
  changed_when: false
  check_mode: false
  tags: [ufw]

- name: Display UFW status
  ansible.builtin.debug:
    var: ufw_status.stdout_lines
  tags: [ufw]